@file:OptIn(ExperimentalTime::class)

package com.lerchenflo.hallenmanager_server.controllers

import com.lerchenflo.hallenmanager_server.database.model.Area
import com.lerchenflo.hallenmanager_server.database.model.CornerPoint
import com.lerchenflo.hallenmanager_server.database.model.Item
import com.lerchenflo.hallenmanager_server.database.repository.AreaRepository
import com.lerchenflo.hallenmanager_server.database.repository.CornerPointRepository
import com.lerchenflo.hallenmanager_server.database.repository.ItemRepository
import org.springframework.boot.context.event.ApplicationReadyEvent
import org.springframework.context.event.EventListener
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

@RestController()
class MainController(
    private val areaRepository: AreaRepository,
    private val itemRepository: ItemRepository,
    private val cornerPointRepository: CornerPointRepository
) {

    @GetMapping
    @RequestMapping("/test")
    fun test(): String {
        return "server found"
    }


    @EventListener(ApplicationReadyEvent::class)
    fun createDefaultArea() {
        if (areaRepository.count() == 0L) {

            val currenttime = Clock.System.now().toEpochMilliseconds().toString()

            //First start with no areas, create the first one
            val defaultarea = areaRepository.save(Area(
                name = "remote Area 1",
                description = "Default autogenerated area",
                createdAt = currenttime,
                lastchangedAt = currenttime,
                lastchangedBy = "server"
            ))

            //DEBUG add default item
            if (itemRepository.count() == 0L) {
                val item = itemRepository.save(Item(
                    areaId = defaultarea.id.toHexString(),
                    title = "first remote item",
                    description = "Autogenerated",
                    color = null,
                    layers = emptyList(),
                    onArea = true,
                    createdAt = Clock.System.now().toEpochMilliseconds().toString(),
                    lastchangedAt = currenttime,
                    lastchangedBy = "server",
                ))

                if (cornerPointRepository.count() == 0L) {
                    cornerPointRepository.save(
                        CornerPoint(
                            itemId = item.itemid.toHexString(),
                            offsetX = 600f,
                            offsetY = 1000f
                        )
                    )

                    cornerPointRepository.save(
                        CornerPoint(
                            itemId = item.itemid.toHexString(),
                            offsetX = 1100f,
                            offsetY = 1000f
                        )
                    )

                    cornerPointRepository.save(
                        CornerPoint(
                            itemId = item.itemid.toHexString(),
                            offsetX = 1100f,
                            offsetY = 1400f
                        )
                    )

                    cornerPointRepository.save(
                        CornerPoint(
                            itemId = item.itemid.toHexString(),
                            offsetX = 600f,
                            offsetY = 1400f
                        )
                    )

                }

            }

            println("first start area created")
        }
    }
}